server:
  port: 8080
  servlet:
    context-path: /fxz

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_fxz?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.fxz.demo.model
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

excel:
  upload:
    path: upload/